# Generated by Django 3.1.7 on 2021-04-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('blog_app', '0016_auto_20210405_1035'),
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
