# Generated by Django 3.1.7 on 2021-04-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_auto_20210405_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelthree',
            name='level',
        ),
        migrations.RemoveField(
            model_name='leveltwo',
            name='level',
        ),
        migrations.DeleteModel(
            name='LevelOne',
        ),
        migrations.DeleteModel(
            name='LevelThree',
        ),
        migrations.DeleteModel(
            name='LevelTwo',
        ),
        migrations.DeleteModel(
            name='TopLevel',
        ),
    ]
