# Generated by Django 3.1.7 on 2021-04-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_auto_20210407_1239'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('profile_app', '0005_auto_20210405_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
