# Generated by Django 3.1.7 on 2021-03-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20210303_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='theme',
            field=models.CharField(max_length=128, unique=True, verbose_name='Заголовок'),
        ),
    ]
