# Generated by Django 3.1.7 on 2021-03-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_article_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='likes',
            new_name='rating',
        ),
    ]
